name: What Day Is It?
on: [push, pull_request]
  #schedule:
  #- cron: "0 0 * * *"
permissions:
  contents: write
jobs:
  set_readme:
     name: set readme
     runs-on: ubuntu-22.04
     steps:
     - name: checkout repo
       uses: actions/checkout@v2
     - name: set readme
       run: |
         current_date=$(date)
         sed -i -e 's/<!--TIME BEGIN-->/<!--TIME BEGIN-->${current_date}/g' README.md
     - uses: stefanzweifel/git-auto-commit-action@v5
       with:
         commit_message: Set Day
         commit_author: github_actions[bot] <github-actions[bot]@users.noreply.github.com>
