name: What Day Is It?
on: [push]
  #schedule:
  #- cron: "0 0 * * *"
permissions:
  contents: write
jobs:
  set_readme:
     name: set readme
     runs-on: ubuntu-22.04
     steps:
     - name: checkout repo
       uses: actions/checkout@v2
     - name: set readme
       run: |
         current_date=$(printf -v date '%(%Y-%m-%d)T\n' -1)
         sed -i -e "s/<!--TIME BEGIN-->.*<!--TIME END-->/<!--TIME BEGIN-->${current_date}<!--TIME END-->/g" README.md
     - uses: stefanzweifel/git-auto-commit-action@v5
       with:
         commit_message: Set Day
         commit_author: github_actions[bot] <github-actions[bot]@users.noreply.github.com>
